//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.Mvc.SmartName.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APS.Mvc.SmartDisplayName.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id
        ///Xml.
        /// </summary>
        internal static string DefaultAcronyms {
            get {
                return ResourceManager.GetString("DefaultAcronyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///an
        ///the.
        /// </summary>
        internal static string DefaultArticles {
            get {
                return ResourceManager.GetString("DefaultArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abaft
        ///aboard
        ///about
        ///above
        ///absent
        ///across
        ///afore
        ///after
        ///against
        ///along
        ///alongside
        ///amid
        ///amidst
        ///among
        ///amongst
        ///anenst
        ///apropos
        ///apud
        ///around
        ///as
        ///aside
        ///astride
        ///at
        ///athwart
        ///atop
        ///barring
        ///before
        ///behind
        ///below
        ///beneath
        ///beside
        ///besides
        ///between
        ///beyond
        ///but
        ///by
        ///circa
        ///concerning
        ///despite
        ///down
        ///during
        ///except
        ///excluding
        ///failing
        ///following
        ///for
        ///forenenst
        ///from
        ///given
        ///in
        ///including
        ///inside
        ///into
        ///lest
        ///like
        ///mid
        ///midst
        ///minus
        ///modulo
        ///near
        ///nigh
        ///next
        ///notwithstanding
        ///o&apos;
        ///apocopic
        ///of
        ///off
        ///on
        ///on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultPrepositions {
            get {
                return ResourceManager.GetString("DefaultPrepositions", resourceCulture);
            }
        }
    }
}
